<?php

declare(strict_types=1);

namespace App\Support\Scramble\Extensions;

use App\Http\Responses\ProblemResponse;
use Dedoc\Scramble\Extensions\TypeToSchemaExtension;
use Dedoc\Scramble\Support\Generator\Response;
use Dedoc\Scramble\Support\Generator\Schema;
use Dedoc\Scramble\Support\Generator\Types\IntegerType;
use Dedoc\Scramble\Support\Generator\Types\ObjectType;
use Dedoc\Scramble\Support\Generator\Types\StringType;
use Dedoc\Scramble\Support\Type\Generic;
use Dedoc\Scramble\Support\Type\Literal\LiteralIntegerType;
use Dedoc\Scramble\Support\Type\ObjectType as ScrambleObjectType;
use Dedoc\Scramble\Support\Type\Type;

class ProblemResponseExtension extends TypeToSchemaExtension
{
    public function shouldHandle(Type $type): bool
    {
        return $type instanceof ScrambleObjectType && $type->isInstanceOf(ProblemResponse::class);
    }

    public function toSchema(Type $type): ObjectType
    {
        $status = 400;
        if ($type instanceof Generic && isset($type->templateTypes[2]) && $type->templateTypes[2] instanceof LiteralIntegerType) {
            $status = $type->templateTypes[2]->value;
        }

        $objectType = new ObjectType;
        $objectType->addProperty('type', (new StringType)
            ->setDescription('A URI reference that identifies the problem type.')
            ->example('https://example.com'));
        $objectType->addProperty('title', (new StringType)
            ->setDescription('A short, human-readable summary of the problem type.')
            ->example('Unprocessable Entity'));
        $objectType->addProperty('status', (new IntegerType)
            ->setDescription('The HTTP status code generated by the origin server.')
            ->example($status));
        $objectType->addProperty('detail', (new StringType)
            ->setDescription('A human-readable explanation specific to this occurrence.')
            ->example('The email field is required.'));
        $objectType->addProperty('timestamp', (new StringType)
            ->setDescription('The time the error occurred in ISO 8601 format.')
            ->example('2026-07-04T02:39:00Z'));
        $objectType->setRequired(['type', 'title', 'status', 'detail', 'timestamp']);

        return $objectType;
    }

    public function toResponse(Type $type): ?Response
    {
        $code = 400;
        if ($type instanceof Generic && isset($type->templateTypes[2]) && $type->templateTypes[2] instanceof LiteralIntegerType) {
            $code = $type->templateTypes[2]->value;
        }

        $schema = new Schema;
        $schema->type = $this->toSchema($type);

        return (new Response($code))
            ->setContent('application/problem+json', $schema)
            ->setDescription('Problem Details for HTTP APIs (RFC 9457)');
    }
}
