<?php

declare(strict_types=1);

namespace App\Support\Scramble\Extensions;

use App\Http\Responses\ProblemResponse;
use Dedoc\Scramble\Extensions\TypeToSchemaExtension;
use Dedoc\Scramble\Support\Generator\Response as OpenApiResponse;
use Dedoc\Scramble\Support\Generator\Schema;
use Dedoc\Scramble\Support\Generator\Types\IntegerType;
use Dedoc\Scramble\Support\Generator\Types\ObjectType;
use Dedoc\Scramble\Support\Generator\Types\StringType;
use Dedoc\Scramble\Support\Type\Generic;
use Dedoc\Scramble\Support\Type\Literal\LiteralIntegerType;
use Dedoc\Scramble\Support\Type\ObjectType as ScrambleObjectType;
use Dedoc\Scramble\Support\Type\Type;

/**
 * RFC 9457 Problem Details Schema Extension for Scramble.
 */
final class ProblemResponseExtension extends TypeToSchemaExtension
{
    /**
     * Determine if this extension should handle the given Scramble type inference.
     */
    public function shouldHandle(Type $type): bool
    {
        return $type instanceof ScrambleObjectType && $type->isInstanceOf(ProblemResponse::class);
    }

    /**
     * Overrides the OpenAPI response generation layer to control HTTP status codes dynamically.
     */
    public function toResponse(Type $type): ?OpenApiResponse
    {
        // Automatically extract the correct dynamic status code
        $code = $this->extractStatusCodeFromGeneric($type);

        $schema = new Schema;
        $schema->type = $this->toSchema($type);

        return (new OpenApiResponse($code))
            ->setContent('application/problem+json', $schema) // Correct RFC 9457 media type
            ->setDescription('Problem Details for HTTP APIs (RFC 9457)');
    }

    /**
     * Constructs the RFC 9457 compliant error JSON envelope.
     */
    public function toSchema(Type $type): ObjectType
    {
        $code = $this->extractStatusCodeFromGeneric($type);

        $objectType = (new ObjectType)
            ->addProperty('type', (new StringType)
                ->setDescription('A URI reference that identifies the problem type.')
                ->example('https://example.com'))
            ->addProperty('title', (new StringType)
                ->setDescription('A short, human-readable summary of the problem type.')
                ->example('Unprocessable Entity'))
            ->addProperty('status', (new IntegerType)
                ->setDescription('The HTTP status code generated by the origin server.')
                ->example($code))
            ->addProperty('detail', (new StringType)
                ->setDescription('A human-readable explanation specific to this occurrence.')
                ->example('The email field is required.'))
            ->addProperty('timestamp', (new StringType)
                ->setDescription('The time the error occurred in ISO 8601 format.')
                ->example('2026-07-04T05:47:00Z'))
            // Fix: Pass a Type object instead of boolean true to allow open dynamic keys compliant with RFC 9457
            ->additionalProperties(new ObjectType);

        $objectType->setRequired(['type', 'title', 'status', 'detail', 'timestamp']);

        return $objectType;
    }

    /**
     * Safely loops through template parameters to find the literal integer status code.
     * Prevents index errors and supports flexible docstring formats.
     */
    private function extractStatusCodeFromGeneric(Type $type): int
    {
        if ($type instanceof Generic && isset($type->templateTypes)) {
            // If templateTypes is a singular object instead of an array
            if ($type->templateTypes instanceof LiteralIntegerType) {
                return $type->templateTypes->value;
            }

            // If templateTypes is an array, iterate to find the status code integer
            if (is_array($type->templateTypes)) {
                foreach ($type->templateTypes as $templateType) {
                    if ($templateType instanceof LiteralIntegerType) {
                        return $templateType->value;
                    }
                }
            }
        }

        return 400; // Safe fallback error code
    }
}
