<?php

declare(strict_types=1);

namespace App\Http\Responses;

use Illuminate\Http\JsonResponse;

/**
 * RFC 9457 Problem Details for HTTP APIs.
 *
 * Generates a standardised JSON problem response with the correct
 * Content-Type header and configurable type URI resolution.
 */
final class ProblemResponse extends JsonResponse
{
    /**
     * @param  string  $title  A short, human-readable summary of the problem type.
     * @param  int  $status  The HTTP status code generated by the origin server.
     * @param  string  $detail  A human-readable explanation of this specific occurrence.
     * @param  string  $typeKey  A type key mapped in config/errors.php, or 'about:blank'.
     * @param  mixed  $errors  Optional field-level validation errors.
     * @param  string  $instance  A clean URI reference identifying the specific occurrence.
     */
    public function __construct(
        string $title,
        int $status,
        string $detail = '',
        string $typeKey = 'about:blank',
        mixed $errors = null,
        string $instance = '',
    ) {
        $payload = [
            'type' => $this->resolveTypeUrl($typeKey),
            'title' => $title,
            'status' => $status,
            'detail' => $detail,
        ];

        if ($instance !== '') {
            $payload['instance'] = $instance;
        }

        if ($errors !== null) {
            $payload['errors'] = $errors;
        }

        parent::__construct(data: $payload, status: $status);

        $this->headers->set('Content-Type', 'application/problem+json');
    }

    /**
     * Resolve the fully-qualified type URI from a key.
     *
     * Resolution order:
     *  1. Return 'about:blank' when the key or configured URL is 'about:blank'.
     *  2. Build from problem_type_url + slug.
     *  3. Build from problem_type_domain + path + slug.
     *  4. Build from app.url + path + slug.
     *  5. Fall back to 'about:blank'.
     */
    private function resolveTypeUrl(string $key): string
    {
        if ($key === 'about:blank') {
            return 'about:blank';
        }

        $configUrl = config('errors.problem_type_url', 'about:blank');

        if (is_string($configUrl) && $configUrl !== 'about:blank') {
            return $this->doBuildUri($configUrl, $key);
        }

        $domain = config('errors.problem_type_domain');

        if (is_string($domain) && $domain !== '') {
            return $this->doBuildUri($domain, $key);
        }

        $appUrl = config('app.url');

        if (is_string($appUrl) && $appUrl !== '') {
            return $this->doBuildUri($appUrl, $key);
        }

        return 'about:blank';
    }

    private function doBuildUri(string $base, string $key): string
    {
        $path = config('errors.problem_type_path', 'problems');
        $path = is_string($path) ? $path : 'problems';

        $slug = config("errors.types.{$key}");

        if (! is_string($slug) || $slug === '') {
            $slug = $key;
        }

        return rtrim($base, '/').'/'.trim($path, '/').'/'.ltrim($slug, '/');
    }
}
