<?php

declare(strict_types=1);

namespace App\Extensions;

use Dedoc\Scramble\Extensions\OperationExtension;
use Dedoc\Scramble\Support\Generator\Operation;
use Dedoc\Scramble\Support\Generator\Response;
use Dedoc\Scramble\Support\Generator\Schema;
use Dedoc\Scramble\Support\Generator\Types\ArrayType;
use Dedoc\Scramble\Support\Generator\Types\IntegerType;
use Dedoc\Scramble\Support\Generator\Types\ObjectType;
use Dedoc\Scramble\Support\Generator\Types\StringType;
use Dedoc\Scramble\Support\RouteInfo;

class CleanErrorResponseContentTypeExtension extends OperationExtension
{
    public function handle(Operation $operation, RouteInfo $routeInfo): void
    {
        foreach ($operation->responses ?? [] as $response) {
            if (! $response instanceof Response) {
                continue;
            }

            if (($response->code ?? 200) < 400) {
                continue;
            }

            if (! isset($response->content['application/problem+json'])) {
                continue;
            }

            unset($response->content['application/json']);

            $this->fixProblemResponseSchema($response);
        }
    }

    private function fixProblemResponseSchema(Response $response): void
    {
        $schema = $response->content['application/problem+json'] ?? null;

        if (! $schema instanceof Schema) {
            return;
        }

        if ($schema->type->type !== 'string') {
            return;
        }

        $examples = $schema->type->examples;
        $description = $schema->type->description;

        $objectType = new ObjectType;
        $objectType->setDescription($description);
        $objectType->examples($examples);

        $objectType->addProperty('type', (new StringType)->setDescription('A URI reference identifying the problem type'));
        $objectType->addProperty('title', (new StringType)->setDescription('A short, human-readable summary of the problem type'));
        $objectType->addProperty('status', (new IntegerType)->setDescription('The HTTP status code generated by the origin server'));
        $objectType->addProperty('message', (new StringType)->setDescription('A human-readable explanation of the problem'));
        $objectType->addProperty('detail', (new StringType)->setDescription('A detailed explanation of the problem'));

        $objectType->setRequired(['type', 'title', 'status', 'message', 'detail']);

        if ($response->code === 422) {
            $errorsType = new ObjectType;
            $errorsType->description = 'Validation errors keyed by field name';
            $errorItems = new ArrayType;
            $errorItems->setItems(new StringType);
            $errorsType->additionalProperties($errorItems);

            $objectType->addProperty('errors', $errorsType);
            $objectType->addRequired(['errors']);
        }

        /** @var Schema $problemSchema */
        $problemSchema = Schema::fromType($objectType);
        $response->content['application/problem+json'] = $problemSchema;
    }
}
