<?php

declare(strict_types=1);

namespace App\Extensions;

use Dedoc\Scramble\Extensions\ExceptionToResponseExtension;
use Dedoc\Scramble\Support\Type\Generic;
use Dedoc\Scramble\Support\Type\Literal\LiteralIntegerType;
use Dedoc\Scramble\Support\Type\ObjectType;
use Dedoc\Scramble\Support\Type\Type;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\RecordsNotFoundException;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class SuppressAutoGeneratedErrorsExtension extends ExceptionToResponseExtension
{
    public function shouldHandle(Type $type): bool
    {
        if (! $type instanceof ObjectType) {
            return false;
        }

        $exceptionClasses = [
            ValidationException::class,
            AuthenticationException::class,
            AuthorizationException::class,
            AccessDeniedHttpException::class,
            ModelNotFoundException::class,
            NotFoundHttpException::class,
            RecordsNotFoundException::class,
        ];

        foreach ($exceptionClasses as $class) {
            if ($type->isInstanceOf($class)) {
                return true;
            }
        }

        // Suppress TooManyRequestsHttpException (which extends HttpException)
        if ($type instanceof Generic && $type->isInstanceOf(HttpException::class)) {
            $codeType = count($type->templateTypes) > 3
                ? ($type->templateTypes[7] ?? null)
                : ($type->templateTypes[0] ?? null);

            return $codeType instanceof LiteralIntegerType && $codeType->value === 429;
        }

        return false;
    }

    public function toResponse(Type $type): null
    {
        return null;
    }
}
